In [35]:
from PIL import Image

gray = Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\fortworth_groundtruth.png').convert('L')

print(gray.size)

gray.save(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\vancouver_groundtruth_gray.png')

(5120, 5120)


In [36]:
import numpy as np

gt_gray = np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\fortworth_groundtruth_gray.png'))

gt_gray[gt_gray == 0] = 6

gt_gray[gt_gray == 29] = 4

gt_gray[gt_gray == 38] = 2

gt_gray[gt_gray == 76] = 3

gt_gray[gt_gray == 90] = 3

gt_gray[gt_gray == 105] = 5

gt_gray[gt_gray == 142] = 0

gt_gray[gt_gray == 150] = 4

gt_gray[gt_gray == 179] = 3

print(gt_gray.shape)

(5120, 5120)


# Read Predicted Maps (Vancouver)

In [37]:
import numpy as np
from PIL import Image

from PIL.Image import Resampling

from sklearn.metrics import classification_report

def open_image(image_path):


    image_array = np.array(Image.open(image_path))

    print(image_array.shape)

    return(image_array)

###

ortho_image_path = r'D:\Nafiseh\building_type\Orthophoto_Vancouver_Predicted_Map_2.tif'

lidar_image_path = r'D:\Nafiseh\building_type\LiDAR_Vancouver_Predicted_Map_2.tif'

gsv_image_path = r'D:\Nafiseh\building_type\GSV_Vancouver_Predicted_Map_2.tif'

gt_image_path = r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\vancouver_test_region\vancouver_groundtruth_gray.png'

##

ortho_image_array = open_image(ortho_image_path)

lidar_image_array = open_image(lidar_image_path)

gsv_image_array = open_image(gsv_image_path)

gt_image_array = open_image(gt_image_path)

### resize arrays to ground truth array size

ortho_image_array_r = np.array(Image.fromarray(ortho_image_array).resize((gt_image_array.shape[0],gt_image_array.shape[1]), resample = Resampling.NEAREST))
                                
lidar_image_array_r = np.array(Image.fromarray(lidar_image_array).resize((gt_image_array.shape[0],gt_image_array.shape[1]), resample = Resampling.NEAREST))

gsv_image_array_r = np.array(Image.fromarray(gsv_image_array).resize((gt_image_array.shape[0],gt_image_array.shape[1]), resample = Resampling.NEAREST))

print(ortho_image_array_r.shape, lidar_image_array_r.shape, gsv_image_array_r.shape)

(255, 381)
(255, 381)
(255, 381)
(2560, 2560)
(2560, 2560) (2560, 2560) (2560, 2560)


# Read Predicted Maps (Fortworth)

In [38]:
import numpy as np
from PIL import Image

from PIL.Image import Resampling

from sklearn.metrics import classification_report

def open_image(image_path):


    image_array = np.array(Image.open(image_path))

    print(image_array.shape)

    return(image_array)

###

ortho_image_path_f = r'D:\Nafiseh\building_type\Orthophoto_Fortworth_Predicted_Map_2.tif'

lidar_image_path_f = r'D:\Nafiseh\building_type\LiDAR_Fortworth_Predicted_Map_2.tif'

gsv_image_path_f = r'D:\Nafiseh\building_type\GSV_Fortworth_Predicted_Map_2.tif'

gt_image_path_f = r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\fortworth_groundtruth_gray.png'

##

ortho_image_array_f = open_image(ortho_image_path_f)

lidar_image_array_f = open_image(lidar_image_path_f)

gsv_image_array_f = open_image(gsv_image_path_f)

gt_image_array_f = open_image(gt_image_path_f)

### resize arrays to ground truth array size

ortho_image_array_f_r = np.array(Image.fromarray(ortho_image_array_f).resize((gt_image_array_f.shape[0],gt_image_array_f.shape[1]), resample = Resampling.NEAREST))
                                
lidar_image_array_f_r = np.array(Image.fromarray(lidar_image_array_f).resize((gt_image_array_f.shape[0],gt_image_array_f.shape[1]), resample = Resampling.NEAREST))
    
gsv_image_array_f_r = np.array(Image.fromarray(gsv_image_array_f).resize((gt_image_array_f.shape[0],gt_image_array_f.shape[1]), resample = Resampling.NEAREST))


print(ortho_image_array_f_r.shape, lidar_image_array_f_r.shape, gsv_image_array_f_r.shape)

(212, 212)
(212, 212)
(212, 212)
(5120, 5120)
(5120, 5120) (5120, 5120) (5120, 5120)


# Show Label Values for Ground Truth and Predicted Maps (Vancouver)

In [39]:
import pandas as pd

# Ground Truth Labels

df_gt = pd.DataFrame({'class name (ground truth)': ['background', 'apartment','office building', 'garage', 'retail', 'industrial', 'house', 'church']}
              ,index = np.unique(gt_image_array))

# Orthophoto and LiDAR Labels

df_ortho_and_lidar = pd.DataFrame({'class name (orthophoto/lidar)': ['industrial', 'institutional', 'office building', 'other', 'residential', 
                                   'retail', 'background']}, index = np.unique(ortho_image_array))


df_gsv = pd.DataFrame({'class name (gsv)': ['apartment', 'church', 'house', 'industrial', 'mixed r/c', 'office building',
                                   'retail', 'background']}, index = np.unique(gsv_image_array))

display(df_gt, df_ortho_and_lidar, df_gsv)

class name (ground truth)
0                  background
29                  apartment
38            office building
90                     garage
105                    retail
142                industrial
150                     house
179                    church

class name (orthophoto/lidar)
0                      industrial
17                  institutional
34                office building
51                          other
68                    residential
85                         retail
255                    background

class name (gsv)
0          apartment
17            church
34             house
51        industrial
68         mixed r/c
85   office building
102           retail
255       background

# Show Label Values for Ground Truth and Predicted Maps (Fortworth)

In [40]:
import pandas as pd

# Ground Truth Labels

df_gt_f = pd.DataFrame({'class name (ground truth)': ['background', 'apartment','office building', 'roof','garage', 'retail', 'industrial', 'house', 'church']}
              ,index = np.unique(gt_image_array_f))

# Orthophoto and LiDAR Labels

df_ortho_and_lidar_f = pd.DataFrame({'class name (orthophoto/lidar)': ['industrial', 'institutional', 'office building', 'other', 'residential', 
                                   'retail', 'background']}, index = np.unique(ortho_image_array_f))

df_gsv_f = pd.DataFrame({'class name (gsv)': ['apartment', 'church', 'industrial', 'mixed r/c', 'office building',
                                   'retail', 'background']}, index = np.unique(gsv_image_array_f))

display(df_gt_f, df_ortho_and_lidar_f)

class name (ground truth)
0                  background
29                  apartment
38            office building
76                       roof
90                     garage
105                    retail
142                industrial
150                     house
179                    church

class name (orthophoto/lidar)
0                      industrial
17                  institutional
34                office building
51                          other
68                    residential
85                         retail
255                    background

# Make Labels Consistent 

In [41]:
def make_gt_labels_same_as_ortho_and_lidar(gt):
    
    gtt = np.copy(gt)

    gtt [gt == 0] = 255 #background

    gtt [(gt == 29) | (gt == 150)] = 68  #residential

    gtt [gt == 38] = 34 #office building

    gtt [(gt == 76) | (gt == 90)] = 51  #garage and roof >> other

    gtt [gt == 105] = 85 #retail

    gtt [gt == 142] = 0 #industrial

    gtt [gt == 179] = 17 #institutional
    
    return(gtt)

def make_gt_labels_same_as_gsv(gt, gsv):
    
        
    gtt = np.copy(gt)

    gtt [gt == 0] = 255 #background

    gtt [gt == 29] = 0  #apartment

    gtt [gt == 38] = 85 #office building

    gtt [gt == 142] = 51 #industrial
    
    gtt [gt == 150] = 34 #house

    gtt [gt == 105] = 102 # retail
    
    gtt [gt == 179] = 17 #church

    gtt [(gt == 76) | (gt == 90)] = 95 #roof and garage >> other
    
    gsv [gsv == 68] = 34  #there is no mixed r/c in ground truth so I relabeld them to house
    
    return(gtt,gsv)

# Vancouver

In [42]:
gt_image_arrayy = make_gt_labels_same_as_ortho_and_lidar(gt_image_array)

print(np.unique(gt_image_arrayy))

gt_image_arrayy_gsv, gsv_image_array_r_new = make_gt_labels_same_as_gsv(gt_image_array, gsv_image_array_r)

print(np.unique(gt_image_arrayy_gsv))

[  0  17  34  51  68  85 255]
[  0  17  34  51  85  95 102 255]


# Fortworth

In [43]:
gt_image_arrayy_f = make_gt_labels_same_as_ortho_and_lidar(gt_image_array_f)

print(np.unique(gt_image_arrayy_f))

gt_image_arrayy_f_gsv, gsv_image_array_r_f_new = make_gt_labels_same_as_gsv(gt_image_array_f, gsv_image_array_f_r)

print(np.unique(gt_image_arrayy_f_gsv))

[  0  17  34  51  68  85 255]
[  0  17  34  51  85  95 102 255]


# Calculate Accuracies for Orthophoto (Vancouver)

In [44]:
from sklearn.metrics import classification_report

class_names =['industrial','institutional','office building','other','residential','retail','background']

print(np.unique(gt_image_arrayy), np.unique(ortho_image_array_r))

print(classification_report(np.ravel(gt_image_arrayy), np.ravel(ortho_image_array_r), target_names = class_names))

[  0  17  34  51  68  85 255] [  0  17  34  51  68  85 255]
                 precision    recall  f1-score   support

     industrial       0.02      0.18      0.04     43668
  institutional       0.00      0.00      0.00     15902
office building       0.03      0.03      0.03    180637
          other       0.01      0.04      0.01    115192
    residential       0.43      0.12      0.19   1214447
         retail       0.23      0.22      0.23    382736
     background       0.85      0.86      0.85   4601018

       accuracy                           0.64   6553600
      macro avg       0.22      0.21      0.19   6553600
   weighted avg       0.69      0.64      0.65   6553600



# Calculate Accuracies for Orthophoto (Fortworth)

In [45]:
from sklearn.metrics import classification_report

class_names =['industrial','institutional','office building','other','residential','retail','background']

print(np.unique(gt_image_arrayy), np.unique(ortho_image_array_r))

print(classification_report(np.ravel(gt_image_arrayy_f), np.ravel(ortho_image_array_f_r), target_names = class_names))

[  0  17  34  51  68  85 255] [  0  17  34  51  68  85 255]
                 precision    recall  f1-score   support

     industrial       0.00      0.00      0.00    444049
  institutional       0.00      0.00      0.00    166926
office building       0.59      0.13      0.21   4421130
          other       0.01      0.03      0.01    315595
    residential       0.02      0.02      0.02    495108
         retail       0.02      0.18      0.04    214216
     background       0.87      0.88      0.87  20157376

       accuracy                           0.70  26214400
      macro avg       0.22      0.18      0.16  26214400
   weighted avg       0.77      0.70      0.71  26214400



# Calculate Accuracies for LiDAR (Vancouver)

In [46]:
from sklearn.metrics import classification_report

class_names = ['industrial', 'institutional','office building','other','residential','retail','background']

print(np.unique(gt_image_arrayy), np.unique(lidar_image_array_r))

print(classification_report(np.ravel(gt_image_arrayy), np.ravel(lidar_image_array_r), target_names = class_names))

[  0  17  34  51  68  85 255] [  0  17  34  51  85 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

     industrial       0.00      0.00      0.00     43668
  institutional       0.00      0.00      0.00     15902
office building       0.04      0.23      0.07    180637
          other       0.07      0.26      0.11    115192
    residential       0.00      0.00      0.00   1214447
         retail       0.00      0.00      0.00    382736
     background       0.82      0.88      0.85   4601018

       accuracy                           0.63   6553600
      macro avg       0.13      0.20      0.15   6553600
   weighted avg       0.58      0.63      0.60   6553600



# # Calculate Accuracies for LiDAR (Fortworth)

In [47]:
from sklearn.metrics import classification_report

class_names = ['industrial', 'institutional','office building','other','residential','retail','background']

print(np.unique(gt_image_arrayy_f), np.unique(lidar_image_array_f_r))

print(classification_report(np.ravel(gt_image_arrayy_f), np.ravel(lidar_image_array_f_r), target_names = class_names))

[  0  17  34  51  68  85 255] [  0  17  34  51  85 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

     industrial       0.05      0.13      0.07    444049
  institutional       0.00      0.06      0.01    166926
office building       0.38      0.07      0.12   4421130
          other       0.00      0.00      0.00    315595
    residential       0.00      0.00      0.00    495108
         retail       0.01      0.03      0.01    214216
     background       0.87      0.87      0.87  20157376

       accuracy                           0.69  26214400
      macro avg       0.19      0.17      0.16  26214400
   weighted avg       0.74      0.69      0.69  26214400



# Calculate Accuracies for GSV (Vancouver)

In [209]:
from sklearn.metrics import classification_report

class_names =['apartment','church', 'house','industrial','office building','other','retail','background']

print(np.unique(gt_image_arrayy_gsv), np.unique(gsv_image_array_r_new))

print(classification_report(np.ravel(gt_image_arrayy_gsv), np.ravel(gsv_image_array_r_new), target_names = class_names))

[  0  17  34  51  85  95 102 255] [  0  17  34  51  85 102 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

      apartment       0.47      0.17      0.25   1095697
         church       0.00      0.00      0.00     15902
          house       0.05      0.15      0.07    118750
     industrial       0.00      0.00      0.00     43668
office building       0.01      0.03      0.02    180637
          other       0.00      0.00      0.00    115192
         retail       0.09      0.05      0.07    382736
     background       0.84      0.89      0.86   4601018

       accuracy                           0.66   6553600
      macro avg       0.18      0.16      0.16   6553600
   weighted avg       0.68      0.66      0.66   6553600



# Calculate Accuracies for GSV (Fortworth)

In [210]:
from sklearn.metrics import classification_report

class_names =['apartment','church', 'house','industrial','office building','other','retail','background']

print(np.unique(gt_image_arrayy_f_gsv), np.unique(gsv_image_array_r_f_new))

print(classification_report(np.ravel(gt_image_arrayy_f_gsv), np.ravel(gsv_image_array_r_f_new), target_names = class_names))

[  0  17  34  51  85  95 102 255] [  0  17  34  51  85 102 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

      apartment       0.00      0.00      0.00    491512
         church       0.01      0.02      0.01    166926
          house       0.00      0.00      0.00      3596
     industrial       0.00      0.00      0.00    444049
office building       0.41      0.30      0.35   4421130
          other       0.00      0.00      0.00    315595
         retail       0.01      0.04      0.01    214216
     background       0.88      0.87      0.88  20157376

       accuracy                           0.72  26214400
      macro avg       0.16      0.15      0.16  26214400
   weighted avg       0.75      0.72      0.73  26214400



# Fusion of Orthophoto and LiDAR

## Ranking Classes Based on F1 Score (Step 1)

## Vancouver

Class                        F1score

1. Orthophoto Background      0.85

2. Orthophoto Background      0.85

3. Orthophoto Retail          0.23

4. Orthophoto Residential     0.19

5. LiDAR Other                0.11

6. LiDAR Office Building      0.07

7. Orthophoto Industrial      0.04

8. Orthophoto Office Building 0.03

9. Orthophoto Other           0.01

10. Orthophoto Institutional  0

11. LiDAR Institutional       0

12. LiDAR Industrial          0

13. LiDAR Retail              0

14. LiDAR Residential         0


## Fortworth

Class                        F1score

1. Orthophoto Background      0.87

2. Orthophoto Background      0.87

3. Orthophoto Office Building 0.21

4. LiDAR Office Building      0.12

5. LiDAR Industrial           0.07

6. Orthophoto Retail          0.04

7. Orthophoto Residential     0.02

8. LiDAR Intitutional         0.01

9. LiDAR Retail               0.01

10. Orthophoto Other          0

11. Orthophoto Industrial     0

12. Orthophoto Institutional  0

13. LiDAR Other               0

14. LiDAR Residential         0


## Vancouver

# Find Corresponding Labels For Each Class

In [48]:
def find_labels(array1, array2, labels):
    
    idx1= [np.where(array1 == l) for l in labels]
    
    idx2 =[np.where(array2 == l) for l in labels]
    
    return (idx1,idx2)

idx1, idx2 = find_labels(ortho_image_array_r, lidar_image_array_r, [0,17,34,51,68,85,255])

In [49]:
########

f1score_fused_l_o = np.multiply(-1,np.ones((ortho_image_array_r.shape))).astype('int')

#########

f1score_fused_l_o [idx2[4]] = 68

f1score_fused_l_o [idx2[5]] = 85

f1score_fused_l_o [idx2[0]] = 0

f1score_fused_l_o [idx2[1]] = 17

f1score_fused_l_o [idx1[1]] = 17

f1score_fused_l_o [idx1[3]] = 51

f1score_fused_l_o [idx1[2]] = 34

f1score_fused_l_o [idx1[0]] = 0

f1score_fused_l_o [idx2[2]] = 34

f1score_fused_l_o [idx2[3]] = 51

f1score_fused_l_o [idx1[4]] = 68

f1score_fused_l_o [idx1[5]] = 85

f1score_fused_l_o [idx2[6]] = 255

f1score_fused_l_o [idx1[6]] = 255

print(np.unique(f1score_fused_l_o))

[  0  17  34  51  68  85 255]


### Show Results (Vancouver)

In [173]:
import matplotlib.pyplot as plt

plt.imshow(f1score_fused_l_o)

plt.axis('off')

plt.show()

## Fortworth

In [51]:
idx1_f, idx2_f = find_labels(ortho_image_array_f_r, lidar_image_array_f_r, [0,17,34,51,68,85,255])

In [52]:
#######

f1score_fused_l_o_f = np.multiply(-1,np.ones((ortho_image_array_f_r.shape))).astype('int')

#########

f1score_fused_l_o_f [idx2_f[4]] = 68

f1score_fused_l_o_f [idx2_f[3]] = 51

f1score_fused_l_o_f [idx1_f[1]] = 17

f1score_fused_l_o_f [idx1_f[0]] = 0

f1score_fused_l_o_f [idx1_f[3]] = 51

f1score_fused_l_o_f [idx2_f[5]] = 85

f1score_fused_l_o_f [idx2_f[1]] = 17

f1score_fused_l_o_f [idx1_f[4]] = 68

f1score_fused_l_o_f [idx1_f[5]] = 85

f1score_fused_l_o_f [idx2_f[0]] = 0

f1score_fused_l_o_f [idx2_f[2]] = 34

f1score_fused_l_o_f [idx1_f[2]] = 34

f1score_fused_l_o_f [idx2_f[6]] = 255

f1score_fused_l_o_f [idx1_f[6]] = 255

print(np.unique(f1score_fused_l_o_f))

[  0  17  34  51  68  85 255]


### Show Results (Fortworth)

In [113]:
import matplotlib.pyplot as plt

plt.imshow(f1score_fused_l_o_f)

plt.axis('off')

plt.show()

## Orthophoto and LiDAR

industrial 0; institutional 17; office building 34; other 51; residential 68; retail 85; background 255

## GSV Relabeled 

apartment 0; church 17; house 34; industrial 51; office building 85; other 95; retail 102; background 255

# Relabel LiDAR-Orthophoto Fused Map to GSV Predicted Map

In [53]:
import numpy as np

def make_lidar_ortho_fused_labels_same_as_gsv(fused_map):
    
    fused_map_c = np.copy(fused_map)

    fused_map_c [fused_map == 51] = 95

    fused_map_c [fused_map == 0] = 51

    fused_map_c [fused_map == 85] = 102

    fused_map_c [fused_map == 34] = 85
    
    return(fused_map_c)

## Vancouver

In [54]:
f1score_fused_l_o_2 = make_lidar_ortho_fused_labels_same_as_gsv(f1score_fused_l_o)

print(np.unique(f1score_fused_l_o_2))

[ 17  51  68  85  95 102 255]


### Show Results

In [361]:
import matplotlib.pyplot as plt

plt.imshow(f1score_fused_l_o_2)

plt.axis('off')

plt.show()

# Calculate Accuracies for Fusion of Orthophoto and LiDAR (Vancouver)

In [55]:
from sklearn.metrics import classification_report

class_names =['church','industrial','residnetial','office building','other','retail','background']

#new_labels = [-1]

#########

#idx_not_102 = np.where(f1score_fused_l_o != 102)

#f1score_fused_l_o_3 = f1score_fused_l_o_2 [idx_not_102]

#gt_image_arrayy_gsv_2 = gt_image_arrayy_gsv[idx_not_102]

#idxx = np.where((f1score_fused_l_o_3 != 33) & (f1score_fused_l_o_3 != 35) & (f1score_fused_l_o_3 != 52) & (f1score_fused_l_o_3 != 119) & (f1score_fused_l_o_3 != 136))
####################

#idxx = np.where(f1score_fused_l_o_2 !=-1)

#f1score_fused_l_o_3 = f1score_fused_l_o_2[idxx]

#gt_image_arrayy_gsv_2 = gt_image_arrayy_gsv[idxx]

print(np.unique(f1score_fused_l_o_2), np.unique(gt_image_arrayy_gsv))

gt_image_arrayy_gsv [(gt_image_arrayy_gsv == 0) | (gt_image_arrayy_gsv == 34)] = 68

print(np.unique(f1score_fused_l_o_2), np.unique(gt_image_arrayy_gsv))

print(classification_report(np.ravel(gt_image_arrayy_gsv), np.ravel(f1score_fused_l_o_2), target_names = class_names))

[ 17  51  68  85  95 102 255] [  0  17  34  51  85  95 102 255]
[ 17  51  68  85  95 102 255] [ 17  51  68  85  95 102 255]
                 precision    recall  f1-score   support

         church       0.00      0.00      0.00     15902
     industrial       0.00      0.00      0.00     43668
    residnetial       0.45      0.12      0.19   1214447
office building       0.04      0.15      0.06    180637
          other       0.12      0.26      0.16    115192
         retail       0.04      0.03      0.03    382736
     background       0.81      0.88      0.85   4601018

       accuracy                           0.65   6553600
      macro avg       0.21      0.20      0.18   6553600
   weighted avg       0.66      0.65      0.63   6553600



## Fortworth

In [56]:
f1score_fused_l_o_f_2 = make_lidar_ortho_fused_labels_same_as_gsv(f1score_fused_l_o_f)

print(np.unique(f1score_fused_l_o_f))

print(np.unique(f1score_fused_l_o_f_2))

[  0  17  34  51  68  85 255]
[ 17  51  68  85  95 102 255]


### Show Results

In [363]:
import matplotlib.pyplot as plt

plt.imshow(f1score_fused_l_o_f_2)

plt.axis('off')

plt.show()

# Calculate Accuracies for Fusion of Orthophoto and LiDAR (Fortworth)

In [57]:
from sklearn.metrics import classification_report

class_names =['church','industrial','residnetial','office building','other','retail','background']

####################

#new_labels = [16, 18, 102]

#idx_not_102_f = np.where(f1score_fused_l_o_f != 102)

#f1score_fused_l_o_f_3 = f1score_fused_l_o_f_2 [idx_not_102_f]

#gt_image_arrayy_f_gsv_2 = gt_image_arrayy_f_gsv[idx_not_102_f]

#idxx_f = np.where((f1score_fused_l_o_f_3 != 16) & (f1score_fused_l_o_f_3 != 18))

#f1score_fused_l_o_f_4 = f1score_fused_l_o_f_3[idxx_f]

#gt_image_arrayy_f_gsv_3 = gt_image_arrayy_f_gsv_2[idxx_f]

#print(np.unique(f1score_fused_l_o_f_4), np.unique(gt_image_arrayy_f_gsv_3))

##########################

gt_image_arrayy_f_gsv_2 = np.copy(gt_image_arrayy_f_gsv)

gt_image_arrayy_f_gsv_2 [(gt_image_arrayy_f_gsv == 0) | (gt_image_arrayy_f_gsv == 34)] = 68

print(np.unique(f1score_fused_l_o_f_2), np.unique(gt_image_arrayy_f_gsv_2))

print(classification_report(np.ravel(gt_image_arrayy_f_gsv_2), np.ravel(f1score_fused_l_o_f_2), target_names = class_names))

[ 17  51  68  85  95 102 255] [ 17  51  68  85  95 102 255]
                 precision    recall  f1-score   support

         church       0.00      0.03      0.01    166926
     industrial       0.05      0.12      0.07    444049
    residnetial       0.03      0.02      0.02    495108
office building       0.50      0.16      0.24   4421130
          other       0.00      0.00      0.00    315595
         retail       0.01      0.05      0.01    214216
     background       0.86      0.88      0.87  20157376

       accuracy                           0.71  26214400
      macro avg       0.21      0.18      0.18  26214400
   weighted avg       0.75      0.71      0.71  26214400



# Ranking Classes Based on F1-Score (Step 2)

## Vancouver

Class                        F1score

1. GSV Background             0.86

2. Fusion Background          0.85

3. GSV apartment              0.25

4. Fusion Residential         0.19

5. Fusion Other               0.16

6. GSV house                  0.07

7. GSV Retail                 0.07

8. Fusion Office Building     0.06

9. Fusion Retail              0.03

10. GSV Office Building       0.02

11. GSV Church                0

12. Fusion Church             0

13. GSV Industrial            0

14. Fusion Industrial         0


## Fortworth

Class                        F1score

1. GSV Background             0.88

2. Fusion Background          0.87

3. GSV Office Building        0.35

4. Fusion Office Building     0.24

5. Fusion Industrial          0.07

6. Fusion Residential         0.02

7. Fusion Retail              0.01

8. GSV Retail                 0.01

9. Fusion Church              0.01

10. GSV Church                0.01

11. Fusion Other              0

12. GSV House                 0

13. GSV Industrial            0

14. GSV Other                 0

## Vancouver

In [58]:
idx1_, _ = find_labels(gsv_image_array_r_new, f1score_fused_l_o_2, [0,17,34,51,85,102,255])

_, idx2_ = find_labels(gsv_image_array_r_new, f1score_fused_l_o_2, [17,51,68,85,95,102,255])

In [59]:
########

f1score_fused_final = np.multiply(-1,np.ones((gsv_image_array_r_new.shape))).astype('int')

#########

f1score_fused_final [idx2_[1]] = 51

f1score_fused_final [idx1_[3]] = 51

f1score_fused_final [idx2_[0]] = 17

f1score_fused_final [idx1_[1]] = 17

f1score_fused_final [idx1_[4]] = 85

f1score_fused_final [idx2_[5]] = 102

f1score_fused_final [idx2_[3]] = 85

f1score_fused_final [idx1_[5]] = 102

f1score_fused_final [idx1_[2]] = 34

f1score_fused_final [idx2_[4]] = 95

f1score_fused_final [idx2_[2]] = 68

f1score_fused_final [idx1_[0]] = 0

f1score_fused_final [idx2_[6]] = 255

f1score_fused_final [idx1_[6]] = 255

print(np.unique(f1score_fused_final))

[  0  34  68  85  95 102 255]


## Fortworth

In [60]:
idx1_f, _ = find_labels(gsv_image_array_r_f_new, f1score_fused_l_o_f_2, [0,17,34,51,85,102,255])

_, idx2_f = find_labels(gsv_image_array_r_f_new, f1score_fused_l_o_f_2, [17,51,68,85,95,102,255])

In [61]:
########

f1score_fused_final_f = np.multiply(-1,np.ones((gsv_image_array_r_f_new.shape))).astype('int')

#########

f1score_fused_final_f [idx1_f[3]] = 51

f1score_fused_final_f [idx1_f[2]] = 34

f1score_fused_final_f [idx2_f[4]] = 95

f1score_fused_final_f [idx1_f[1]] = 17

f1score_fused_final_f [idx2_f[0]] = 17

f1score_fused_final_f [idx1_f[5]] = 102

f1score_fused_final_f [idx2_f[5]] = 102

f1score_fused_final_f [idx2_f[2]] = 68

f1score_fused_final_f [idx2_f[1]] = 51

f1score_fused_final_f [idx2_f[3]] = 85

f1score_fused_final_f [idx1_f[4]] = 85

f1score_fused_final_f [idx2_f[6]] = 255

f1score_fused_final_f [idx1_f[6]] = 255


print(np.unique(f1score_fused_final_f))

[ 17  51  68  85 102 255]


# Calculate Accuracies For Final Fused Map (Vancouver)

## Pixel-Based Accuracy Assessment

In [62]:
import numpy as np

from sklearn.metrics import classification_report

class_names =['apartment','church','house','industrial','residential','office building','other','retail','background']

#new_labels = [-1]

#############

#idxx = np.where((f1score_fused_final != 35) & (f1score_fused_final != 50) & (f1score_fused_final != 52) & (f1score_fused_final != 68) & (f1score_fused_final != 69)
         
         #& (f1score_fused_final != 94) & (f1score_fused_final != 101) & (f1score_fused_final != 102) & (f1score_fused_final != 112) &
         
         #(f1score_fused_final != 118) & (f1score_fused_final != 119) & (f1score_fused_final != 120) & (f1score_fused_final != 129) & 
         
         #(f1score_fused_final != 135) & (f1score_fused_final != 136) & (f1score_fused_final != 153) & (f1score_fused_final != 170) &
         
         #(f1score_fused_final != 180) & (f1score_fused_final != 187) & (f1score_fused_final != 204))
        
################     

#idxx = np.where(f1score_fused_final != -1)        

#f1score_fused_final_2 = f1score_fused_final[idxx]

#gt_image_arrayy_gsv_2 = gt_image_arrayy_gsv[idxx]

print(np.unique(gt_image_arrayy_gsv), np.unique(f1score_fused_final))

print(classification_report(np.ravel(gt_image_arrayy_gsv), np.ravel(f1score_fused_final), target_names = class_names))

[ 17  51  68  85  95 102 255] [  0  34  68  85  95 102 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average

                 precision    recall  f1-score   support

      apartment       0.00      0.00      0.00         0
         church       0.00      0.00      0.00     15902
          house       0.00      0.00      0.00         0
     industrial       0.00      0.00      0.00     43668
    residential       0.41      0.09      0.15   1214447
office building       0.00      0.00      0.00    180637
          other       0.13      0.26      0.17    115192
         retail       0.00      0.00      0.00    382736
     background       0.81      0.91      0.86   4601018

       accuracy                           0.66   6553600
      macro avg       0.15      0.14      0.13   6553600
   weighted avg       0.65      0.66      0.63   6553600



## Object-Based Accuracy Assessment

In [63]:
from PIL import Image

import numpy as np

import pandas as pd

from sklearn.metrics import classification_report

def make_labels_same_as_gt(array):
    
    array [array == 17] = 1
    
    array [array == 34] = 2
    
    array [array == 51] = 3
    
    array [array == 68] = 0
    
    array [array == 85] = 4
    
    array [array == 95] = 5
    
    array [array == 102] = 6
    
    array [array == 255] = 7
    
    return(array)

######################################## Labels Guide #####################################################

# 17 >> church, 34 >> house, 51 >> industrial, 68 >> residential, 85 >> office building, 102 >> retail, 255 >> background

# 0 >> apartment, 1 >> church, 2 >> house, 3 >> industrial, 4 >> office building, 5 >> other, 6 >> retail, 7 >> background

###########################################################################################################

class_names = ['apartment','church','house','industrial','office building','other','retail','background']

df = pd.read_csv('D:/Nafiseh/building_type/vancouver_f1_score_fused_zst_majority_2_spj.csv')

gt = np.array(df['GT_gsv'])

predictions = make_labels_same_as_gt(np.array(df['gridcode']))

print(classification_report(gt, predictions, target_names = class_names))

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average

                 precision    recall  f1-score   support

      apartment       0.72      0.39      0.50       109
         church       0.00      0.00      0.00        13
          house       0.27      0.20      0.23        30
     industrial       0.00      0.00      0.00         3
office building       0.00      0.00      0.00         0
          other       0.00      0.00      0.00         5
         retail       0.00      0.00      0.00         7
     background       0.27      1.00      0.42        19

       accuracy                           0.36       186
      macro avg       0.16      0.20      0.14       186
   weighted avg       0.50      0.36      0.38       186



### Confusion Matrix

#### F1 Score Fusion

In [18]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

import pandas as pd


def make_labels_same_as_gt(array):
    
    array [array == 17] = 179
    
    array [array == 34] = 150
    
    array [array == 51] = 142
    
    array [array == 68] = 29
    
    array [array == 85] = 38
    
    array [array == 95] = 90
    
    array [array == 102] = 105
    
    array [array == 255] = 0
    
    return(array)

######################################## Labels Guide #####################################################

# 17 >> church, 34 >> house, 51 >> industrial, 68 >> residential, 85 >> office building, 102 >> retail, 255 >> background

# 0 >> background, 29 >> apartment, 38 >> office building, 90 >> garage, 105 >> retail, 142 >> industrial, 150 >> house, 179 >> church

###########################################################################################################

class_names = ['background','apartment','office building','other','retail','industrial','house','church']

df = pd.read_csv('D:/Nafiseh/building_type/vancouver_f1_score_fused_spj_new.csv')

gt = np.array(df['GT'])

predictions = make_labels_same_as_gt(np.array(df['gridcode']))

plt.rcParams['font.size'] = 10

disp = ConfusionMatrixDisplay(confusion_matrix(gt,predictions), display_labels = class_names)

disp.plot()

#plt.savefig('D:/Nafiseh/building_type/confusion_matrix_f1_score_fusion_vancouver.tif')

plt.show()

#### Fuzzy Fusion

In [149]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

import pandas as pd


def make_labels_same_as_gt(array):
    
    array [array == 4] = 29
    
    array [array == 5] = 105
    
    return(array)

######################################## Labels Guide #####################################################

# 17 >> church, 34 >> house, 51 >> industrial, 68 >> residential, 85 >> office building, 102 >> retail, 255 >> background

# 0 >> background, 29 >> apartment, 38 >> office building, 90 >> garage, 105 >> retail, 142 >> industrial, 150 >> house, 179 >> church

###########################################################################################################

class_names = ['background','apartment','office building','other','retail','industrial','house','church']

df = pd.read_csv('D:/Nafiseh/building_type/vancouver_f1_score_fused_spj_new.csv')

gt = np.array(df['GT'])

predictions = make_labels_same_as_gt(np.array(df['Fuzzy_Fusion']))

plt.rcParams['font.size'] = 10

plt.rcParams['figure.figsize'] = (200, 100)

disp = ConfusionMatrixDisplay(confusion_matrix(gt,predictions), display_labels = class_names)

disp.plot()

#plt.savefig('D:/Nafiseh/building_type/confusion_matrix_f1_score_fusion_vancouver.tif')

plt.show()

# Visualize and Save Results (Vancouver)

In [280]:
def visualize_and_save_figure(fusion_array, path):
    
    blue_patch = mpatches.Patch(color = 'blue', label='apartment')

    cyan_patch = mpatches.Patch(color = 'cyan', label='church')
    
    green_patch = mpatches.Patch(color = 'green', label = 'house')
    
    orange_patch = mpatches.Patch(color = 'orange', label = 'industrial')
    
    #cyan_patch = mpatches.Patch(color = 'cyan',label = 'institutional')
    
    #olive_patch = mpatches.Patch(color = 'olive', label = 'residential')
    
    darkred_patch = mpatches.Patch(color = 'darkred', label = 'office building')

    #red_patch = mpatches.Patch(color = 'red', label = 'other')
    
    #olive_patch = mpatches.Patch(color = 'olive', label = 'residential')

    magenta_patch = mpatches.Patch(color = 'magenta', label = 'retail')

    yellow_patch = mpatches.Patch(color = 'yellow', label = 'background')

    colors = ['blue','cyan','green','orange','darkred','magenta', 'yellow']
    
    u = np.unique(fusion_array)
    
    #color_bins_ortho = [-1, 16, 33, 50, 67, 84, 254, 256]  
    
    #color_bins_lidar = [-1, 16, 33, 50, 84, 254, 256]
    
    #color_bins_gsv = [-1, 16, 33, 50, 84, 101, 254, 256]
    
    #color_bins_f_1 = [-1, 16, 33, 50, 67, 84, 254, 256]
    
    #color_bins_f_1_final = [16, 50, 67, 84, 94, 101, 254, 256]
       
    #color_bins = [-1,33,67,84,94,101,254,256]
    
    #color_bins_gsv = [-1,  16,  33,  50,  84, 101, 254, 256]
    
    #color_bins_f = [16, 50, 67, 84, 101, 254, 256]
 
    color_bins_gsv_f = [-1,  16,  33,  50,  84, 101, 254, 256]
    
    #color_bins_f_gt = [  -1,  16,  33,  50,  84,  94, 101, 254, 256]
    
    #print(color_bins)
    
    #extent = [-123.136140, -123.129303, 49.280349, 49.284829]  # vancouver
    
    extent_f = [-97.340242, -97.326509, 32.746281, 32.757833]  # fortworth

    cmap_listed = ListedColormap(colors)
    
    ax = plt.gca()

    ax.get_xaxis().get_major_formatter().set_useOffset(False)
    
    ax.get_yaxis().get_major_formatter().set_useOffset(False)
    
    ax.tick_params(labeltop = True, labelright = True)
    
    plt.rcParams['font.family'] = 'Times New Roman'
    
    plt.rcParams['font.size'] = 80
    
    plt.rcParams['figure.figsize'] = [160, 80]

    plt.imshow(fusion_array, cmap = cmap_listed, norm = BoundaryNorm(color_bins_gsv_f, len(color_bins_gsv_f)), extent = extent_f)
    
    plt.xlabel('Longitude (deg)', font = 'Times New Roman', fontsize = 100, fontweight = 'bold')
    
    plt.ylabel('Latitude (deg)', font = 'Times New Roman', fontsize = 100, fontweight = 'bold')

    plt.legend(handles = [blue_patch, cyan_patch, green_patch, orange_patch, darkred_patch, magenta_patch, yellow_patch], loc = 'lower center',bbox_to_anchor = (-0.1,-0.15))

    #plt.xticks(np.arange(-123.136140, -123.129303, 0.003))  # vancouver
    
    plt.xticks(np.arange(-97.340242, -97.326509, 0.005))
    
    #plt.yticks(np.arange(49.280349, 49.284829, 0.002))  # vancouver
    
    plt.yticks(np.arange(32.746281,32.757833,0.005))
    
    plt.axis('on')

    plt.savefig(path)

    plt.show()

# Create Subplots (Vancouver)

In [65]:
from PIL import Image

import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

    
blue_patch = mpatches.Patch(color = 'blue', label='apartment')

cyan_patch = mpatches.Patch(color = 'cyan', label='church')

green_patch = mpatches.Patch(color = 'green', label = 'house')

orange_patch = mpatches.Patch(color = 'orange', label = 'industrial')

olive_patch = mpatches.Patch(color = 'olive', label = 'residential')

darkred_patch = mpatches.Patch(color = 'darkred', label = 'office building')

red_patch = mpatches.Patch(color = 'red', label = 'other')

magenta_patch = mpatches.Patch(color = 'magenta', label = 'retail')

yellow_patch = mpatches.Patch(color = 'yellow', label = 'background')

fig, axes = plt.subplots(2,2)

plt.rcParams['font.family'] = 'Times New Roman'

plt.rcParams['font.size'] = 300

plt.rcParams['figure.figsize'] = (300, 150)

extent = [-123.136140, -123.129303, 49.280349, 49.284829]

################# subplot 1 ########################

colors_gt = ['blue','cyan','green','orange','darkred','red','magenta', 'yellow']

cmap_listed_gt = ListedColormap(colors_gt)

u1 = list(np.unique(gt_image_arrayy_gsv)-np.array([1])) + [256]

axes[0,0].imshow(gt_image_arrayy_gsv, cmap = cmap_listed_gt, extent = extent, norm = BoundaryNorm(u1, len(u1)))

#axes[0,0].legend(handles = [blue_patch, cyan_patch,green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch],
                #loc = 'lower left', prop = {'size': 60}, bbox_to_anchor = (-0.2,-0.15))

axes[0,0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0,0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0,0].tick_params(labeltop = True, labelbottom = False, labelright = False)

axes[0,0].set_xlabel('(a)',fontsize = 250, fontweight = 'bold')

axes[0,0].set_ylabel('Latitude', fontsize = 250, fontweight = 'bold')

axes[0,0].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3), fontsize = 250)

axes[0,0].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3), fontsize = 250)

################### subplot 2 #######################

colors_gsv = ['blue','cyan','green','orange','darkred','magenta','yellow']

cmap_listed_gsv = ListedColormap(colors_gsv)

u2 = list(np.unique(gsv_image_array_r_new)-np.array([1])) + [256]

axes[0,1].imshow(gsv_image_array_r_new, cmap = cmap_listed_gsv, extent = extent, norm = BoundaryNorm(u2, len(u2)))

#axes[0,1].legend(handles = [blue_patch, cyan_patch,green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch],
                #loc = 'lower left', prop={'size':60}, bbox_to_anchor = (-0.1,-0.15))

axes[0,1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0,1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0,1].tick_params(labeltop = True, labelbottom = False, labelright = True, labelleft=False)

axes[0,1].set_xlabel('(b)',fontsize = 250, fontweight = 'bold')

#axes[0,1].set_ylabel('Latitude', fontsize = 20, fontweight = 'bold')

axes[0,1].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3), fontsize = 250)

axes[0,1].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3), fontsize = 250)

#################### subplot 3 ###########################

colors_f1_score = ['blue','green','olive','darkred','red','magenta', 'yellow']

cmap_listed_f1_score = ListedColormap(colors_f1_score)

u3 = list(np.unique(f1score_fused_final)-np.array([1])) + [256]

axes[1,0].imshow(f1score_fused_final, cmap = cmap_listed_f1_score, extent = extent, norm = BoundaryNorm(u3,len(u3)))

#axes[1,0].legend(handles = [cyan_patch, orange_patch, olive_patch, darkred_patch, magenta_patch, yellow_patch], loc ='lower left',
                #prop ={'size': 60}, bbox_to_anchor = (-0.1,-0.15))

axes[1,0].legend(handles=[blue_patch, cyan_patch,green_patch, orange_patch, olive_patch, darkred_patch, red_patch, magenta_patch, yellow_patch], loc = 'lower left', prop = {'size': 350},
                bbox_to_anchor = (-1.1,-0.15))     

axes[1,0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1,0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1,0].tick_params(labeltop = False, labelright = False, pad = 80)

axes[1,0].set_xlabel('Longitude \n \n (c)',fontsize = 250, fontweight = 'bold')

axes[1,0].set_ylabel('Latitude', fontsize = 250, fontweight = 'bold')

axes[1,0].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3), fontsize = 250)

axes[1,0].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3), fontsize = 250)

################### subplot 4 ##############################

colors_fuzzy = ['olive','darkred','yellow']

cmap_listed_fuzzy = ListedColormap(colors_fuzzy)

gompertz_vancouver = np.array(Image.open('D:/Nafiseh/building_type/vancouver_gompertz_fuse.tif'))

u4 = list(np.unique(gompertz_vancouver)-np.array([1])) + [256]

axes[1,1].imshow(gompertz_vancouver, cmap = cmap_listed_fuzzy, extent = extent, norm = BoundaryNorm(u4, len(u4)))

#axes[1,1].legend(handles=[green_patch,orange_patch,olive_patch,magenta_patch,yellow_patch], loc = 'lower left', prop = {'size': 60},
                #bbox_to_anchor = (-0.1,-0.15))

axes[1,1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1,1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1,1].tick_params(labeltop = False, labelright = True, labelleft=False, pad = 30)

axes[1,1].set_xlabel('Longitude \n \n (d)',fontsize = 250, fontweight = 'bold')

#axes[1,1].set_ylabel('Latitude', fontsize = 20, fontweight = 'bold')

axes[1,1].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3), fontsize = 250)

axes[1,1].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3), fontsize = 250)

plt.tight_layout()

plt.savefig('D:/Nafiseh/building_type/Building_Type_Manuscript/Figures/vancouver_subplots_3.tif',bbox_inches='tight')

plt.show()

In [33]:
gompertz_vancouver = np.array(Image.open('D:/Nafiseh/building_type/vancouver_gompertz_fuse.tif'))

u4 = list(np.unique(gompertz_vancouver)-np.array([1])) + [256]

print(u4)

[67, 84, 254, 256]


## Visualize Orthophoto Classification Map

In [31]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

Image.fromarray(ortho_image_array_r).save('D:/Nafiseh/building_type/vancouver_ortho_classification_image.png')

np.save('D:/Nafiseh/building_type/vancouver_ortho_classification.npy', ortho_image_array_r)

file_path_vancouver_ortho = 'D:/Nafiseh/building_type/vancouver_ortho_classification.png'

visualize_and_save_figure(ortho_image_array_r, file_path_vancouver_ortho)

## Visualize LiDAR Classification Map

In [36]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

#print(np.unique(lidar_image_array_r))

Image.fromarray(lidar_image_array_r).save('D:/Nafiseh/building_type/vancouver_lidar_classification_image.png')

np.save('D:/Nafiseh/building_type/vancouver_lidar_classification.npy', lidar_image_array_r)

file_path_vancouver_lidar = 'D:/Nafiseh/building_type/vancouver_lidar_classification.png'

visualize_and_save_figure(lidar_image_array_r, file_path_vancouver_lidar)

## Visualize GSV Classification Map

In [224]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

#print(np.unique(gsv_image_array_r_new))

Image.fromarray(gsv_image_array_r_new).save('D:/Nafiseh/building_type/vancouver_gsv_classification_image.png')

np.save('D:/Nafiseh/building_type/vancouver_gsv_classification.npy', gsv_image_array_r)

file_path_vancouver_gsv = 'D:/Nafiseh/building_type/vancouver_gsv_classification_2.png'

visualize_and_save_figure(gsv_image_array_r_new, file_path_vancouver_gsv)

## Visualize Fused Classification Map (Step 1)

In [51]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

#print(np.unique(f1score_fused_l_o_2))

print(np.unique(f1score_fused_l_o_2))

Image.fromarray(f1score_fused_l_o_2).save('D:/Nafiseh/building_type/vancouver_f1_score_fused_step_1_classification_final_image.png')

np.save('D:/Nafiseh/building_type/vancouver_f1_score_fused_step_1_classification_final.npy', f1score_fused_l_o_2)

file_path_vancouver_fused_step_1 = 'D:/Nafiseh/building_type/vancouver_f1_score_fused_step_1_classification_final.png'

visualize_and_save_figure(f1score_fused_l_o_2, file_path_vancouver_fused_step_1)

## Visualize Fused Classification Map

In [164]:
import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

Image.fromarray(f1score_fused_final).save('D:/Nafiseh/building_type/vancouver_f1_score_fused_image_3.png')

np.save('D:/Nafiseh/building_type/vancouver_f1_score_fused_3.npy',f1score_fused_final)

#f1score_fused_final = np.load('D:/Nafiseh/building_type/vancouver_f1_score_fused.npy')

#print(np.unique(f1score_fused_final))

file_path_vancouver = 'D:/Nafiseh/building_type/vancouver_f1_score_fused_3.png'

visualize_and_save_figure(f1score_fused_final, file_path_vancouver)

# Calculate Accuracies For Final Fused Map (Fortworth)

## Pixel-Based Accuracy Assessment

In [66]:
import numpy as np

from sklearn.metrics import classification_report

class_names =['apartment','church','house','industrial','residential','office building','other','retail','background']

#new_labels = [-1]

#############

#idxx = np.where((f1score_fused_final != 35) & (f1score_fused_final != 50) & (f1score_fused_final != 52) & (f1score_fused_final != 68) & (f1score_fused_final != 69)
         
         #& (f1score_fused_final != 94) & (f1score_fused_final != 101) & (f1score_fused_final != 102) & (f1score_fused_final != 112) &
         
         #(f1score_fused_final != 118) & (f1score_fused_final != 119) & (f1score_fused_final != 120) & (f1score_fused_final != 129) & 
         
         #(f1score_fused_final != 135) & (f1score_fused_final != 136) & (f1score_fused_final != 153) & (f1score_fused_final != 170) &
         
         #(f1score_fused_final != 180) & (f1score_fused_final != 187) & (f1score_fused_final != 204))
        
################    

#idxx_f = np.where(f1score_fused_final_f != -1)        

#f1score_fused_final_f_2 = f1score_fused_final_f[idxx_f]

#gt_image_arrayy_f_gsv_2 = gt_image_arrayy_f_gsv[idxx_f]

print(np.unique(gt_image_arrayy_f_gsv), np.unique(f1score_fused_final_f))

print(classification_report(np.ravel(gt_image_arrayy_f_gsv), np.ravel(f1score_fused_final_f), target_names = class_names))

[  0  17  34  51  85  95 102 255] [ 17  51  68  85 102 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average

                 precision    recall  f1-score   support

      apartment       0.00      0.00      0.00    491512
         church       0.00      0.00      0.00    166926
          house       0.00      0.00      0.00      3596
     industrial       0.09      0.10      0.10    444049
    residential       0.00      0.00      0.00         0
office building       0.43      0.38      0.40   4421130
          other       0.00      0.00      0.00    315595
         retail       0.01      0.05      0.02    214216
     background       0.86      0.89      0.88  20157376

       accuracy                           0.75  26214400
      macro avg       0.16      0.16      0.15  26214400
   weighted avg       0.74      0.75      0.74  26214400



## Object-Based Accuracy Assessment

In [67]:
from PIL import Image

import numpy as np

import pandas as pd

from sklearn.metrics import classification_report

def make_labels_same_as_gt(array):
    
    array [(array == 0) | (array == 34) | (array == 68)] = 4
    
    array [array == 17] = 1
    
    array [array == 51] = 0
    
    array [array == 85] = 2
    
    array [array == 95] = 3
    
    array [array == 102] = 5
    
    array [array == 255] = 6
    
    return(array)

######################################## Labels Guide #####################################################

# 17 >> church, 51 >> industrial, 68 >> residential, 85 >> office building, 102 >> retail, 255 >> background

# 0 >> industrial, 1 >> institutional, 2 >> office building, 3 >> other, 4 >> residential, 5 >> retail, 6 >> background

###########################################################################################################

class_names = ['industrial','instiutional','office building','other','residential','retail','background']

df = pd.read_csv('D:/Nafiseh/building_type/fortworth_f1_score_fused_zst_majority_spj.csv', sep = '\t')

gt = np.array(df['GT_2'])

predictions_f = make_labels_same_as_gt(np.array(df['gridcode']))

#print(np.unique(predictions_f))

print(classification_report(gt, predictions_f, target_names = class_names))

KeyError: 'GT_2'

### Confusion Matrix

#### F1 Score Fusion

In [68]:
from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay

def make_labels_same_as_gt(array):
    
    array [(array == 0) | (array == 34) | (array == 68)] = 4
    
    array [array == 17] = 1
    
    array [array == 51] = 0
    
    array [array == 85] = 2
    
    array [array == 95] = 3
    
    array [array == 102] = 5
    
    array [array == 255] = 6
    
    return(array)

######################################## Labels Guide #####################################################

# 17 >> church, 51 >> industrial, 68 >> residential, 85 >> office building, 102 >> retail, 255 >> background

# 0 >> industrial, 1 >> institutional, 2 >> office building, 3 >> other, 4 >> residential, 5 >> retail, 6 >> background

###########################################################################################################

class_names = ['industrial','instiutional','office building','other','residential','retail','background']

df = pd.read_csv('D:/Nafiseh/building_type/fortworth_f1_score_fused_zst_majority_spj.csv')

gt = np.array(df['GT_2'])

plt.rcParams['font.size'] = 10

predictions_f = make_labels_same_as_gt(np.array(df['gridcode']))

disp = ConfusionMatrixDisplay(confusion_matrix(gt, predictions_f), display_labels = class_names)

disp.plot()

plt.show()

# Save Results (Fortworth)

# Visualize GSV Classification Map

In [281]:
import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

Image.fromarray(gsv_image_array_r_f_new).save('D:/Nafiseh/building_type/fortworth_gsv_classification_image.png')

np.save('D:/Nafiseh/building_type/fortworth_gsv_classification.npy',gsv_image_array_r_f_new)

#gsv_image_array_r_f_new = np.load('D:/Nafiseh/building_type/fortworth_gsv_classification.npy')

#print(np.unique(gsv_image_array_r_f_new))

file_path_fortworth = 'D:/Nafiseh/building_type/fortworth_gsv_classification_image_3.png'

visualize_and_save_figure(gsv_image_array_r_f_new,file_path_fortworth)

In [179]:
import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

Image.fromarray(f1score_fused_final_f).save('D:/Nafiseh/building_type/fortworth_gsv_classification_image.png')

np.save('D:/Nafiseh/building_type/fortworth_f1_score_fused_3.npy',f1score_fused_final_f)

#f1score_fused_final_f = np.load('D:/Nafiseh/building_type/fortworth_f1_score_fused_2.npy')

print(np.unique(f1score_fused_final_f))

file_path_fortworth = 'D:/Nafiseh/building_type/fortworth_f1_score_fused_3.png'

visualize_and_save_figure(f1score_fused_final_f,file_path_fortworth)

[ 17  51  68  85 102 255]


# Create Subplots (Fortworth)

In [70]:
from PIL import Image

import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

    
blue_patch = mpatches.Patch(color = 'blue', label='apartment')

cyan_patch = mpatches.Patch(color = 'cyan', label='church')

green_patch = mpatches.Patch(color = 'green', label = 'house')

orange_patch = mpatches.Patch(color = 'orange', label = 'industrial')

olive_patch = mpatches.Patch(color = 'olive', label = 'residential')

darkred_patch = mpatches.Patch(color = 'darkred', label = 'office building')

red_patch = mpatches.Patch(color = 'red', label = 'other')

magenta_patch = mpatches.Patch(color = 'magenta', label = 'retail')

yellow_patch = mpatches.Patch(color = 'yellow', label = 'background')

fig, axes = plt.subplots(2,2)

plt.rcParams['font.family'] = 'Times New Roman'

plt.rcParams['font.size'] = 300

plt.rcParams['figure.figsize'] = (300, 150)

extent_f = [-97.340242, -97.326509, 32.746281, 32.757833]

################# subplot 1 ########################

colors_gt = ['blue','cyan','green','orange','darkred','red','magenta', 'yellow']

cmap_listed_gt = ListedColormap(colors_gt)

u1 = list(np.unique(gt_image_arrayy_f_gsv)-np.array([1])) + [256]

axes[0,0].imshow(gt_image_arrayy_f_gsv, cmap = cmap_listed_gt, extent = extent_f, norm = BoundaryNorm(u1, len(u1)))

#axes[0,0].legend(handles = [blue_patch, cyan_patch,green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch],
                #loc = 'lower left', prop = {'size': 60}, bbox_to_anchor = (-0.2,-0.15))

axes[0,0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0,0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0,0].tick_params(labeltop = True, labelbottom = False, labelright = False)

axes[0,0].set_xlabel('(a)',fontsize = 250, fontweight = 'bold')

axes[0,0].set_ylabel('Latitude', fontsize = 250, fontweight = 'bold')

axes[0,0].set_xticks(np.round(np.arange(-97.340242, -97.326509, 0.005),3), fontsize = 250)

axes[0,0].set_yticks(np.round(np.arange(32.746281,32.757833,0.005),3), fontsize = 250)

################### subplot 2 #######################

colors_gsv = ['blue','cyan','green','orange','darkred','red','magenta','yellow']

cmap_listed_gsv = ListedColormap(colors_gsv)

u2 = list(np.unique(gsv_image_array_r_f_new)-np.array([1])) + [256]

axes[0,1].imshow(gsv_image_array_r_f_new, cmap = cmap_listed_gsv, extent = extent_f, norm = BoundaryNorm(u2, len(u2)))

#axes[0,1].legend(handles = [blue_patch, cyan_patch,green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch],
                #loc = 'lower left', prop={'size':60}, bbox_to_anchor = (-0.1,-0.15))

axes[0,1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0,1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0,1].tick_params(labeltop = True, labelbottom = False, labelright = True, labelleft=False)

axes[0,1].set_xlabel('(b)',fontsize = 250, fontweight = 'bold')

#axes[0,1].set_ylabel('Latitude', fontsize = 20, fontweight = 'bold')

axes[0,1].set_xticks(np.round(np.arange(-97.340242, -97.326509, 0.005),3), fontsize = 250)

axes[0,1].set_yticks(np.round(np.arange(32.746281,32.757833,0.005),3), fontsize = 250)

#################### subplot 3 ###########################

colors_f1_score = ['cyan','orange','olive','darkred','magenta', 'yellow']

cmap_listed_f1_score = ListedColormap(colors_f1_score)

u3 = list(np.unique(f1score_fused_final_f)-np.array([1])) + [256]

axes[1,0].imshow(f1score_fused_final_f, cmap = cmap_listed_f1_score, extent = extent_f, norm = BoundaryNorm(u3,len(u3)))

#axes[1,0].legend(handles = [cyan_patch, orange_patch, olive_patch, darkred_patch, magenta_patch, yellow_patch], loc ='lower left',
                #prop ={'size': 60}, bbox_to_anchor = (-0.1,-0.15))

axes[1,0].legend(handles=[blue_patch, cyan_patch,green_patch, orange_patch, olive_patch, darkred_patch, red_patch, magenta_patch, yellow_patch], loc = 'lower left', prop = {'size': 350},
                bbox_to_anchor = (-1.1,-0.15))     

axes[1,0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1,0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1,0].tick_params(labeltop = False, labelright = False, pad = 120)

axes[1,0].set_xlabel('Longitude \n \n (c)',fontsize = 250, fontweight = 'bold')

axes[1,0].set_ylabel('Latitude', fontsize = 250, fontweight = 'bold')

axes[1,0].set_xticks(np.round(np.arange(-97.340242, -97.326509, 0.005),3), fontsize = 250)

axes[1,0].set_yticks(np.round(np.arange(32.746281,32.757833,0.005),3), fontsize = 250)

################### subplot 4 ##############################

colors_fuzzy = ['green','orange','olive','magenta','yellow']

cmap_listed_fuzzy = ListedColormap(colors_fuzzy)

gompertz_fortworth = np.array(Image.open('D:/Nafiseh/building_type/fortworth_gompertz_fused.tif'))

u4 = list(np.unique(gompertz_fortworth)-np.array([1])) + [256]

axes[1,1].imshow(gompertz_fortworth, cmap = cmap_listed_fuzzy, extent = extent_f, norm = BoundaryNorm(u4, len(u4)))

#axes[1,1].legend(handles=[green_patch,orange_patch,olive_patch,magenta_patch,yellow_patch], loc = 'lower left', prop = {'size': 60},
                #bbox_to_anchor = (-0.1,-0.15))
 

axes[1,1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1,1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1,1].tick_params(labeltop = False, labelright = True, labelleft=False)

axes[1,1].set_xlabel('Longitude \n \n (d)',fontsize = 250, fontweight = 'bold')

#axes[1,1].set_ylabel('Latitude', fontsize = 20, fontweight = 'bold')

axes[1,1].set_xticks(np.round(np.arange(-97.340242, -97.326509, 0.005),3), fontsize = 250)

axes[1,1].set_yticks(np.round(np.arange(32.746281,32.757833,0.005),3), fontsize = 250)

plt.tight_layout()

plt.savefig('D:/Nafiseh/building_type/Building_Type_Manuscript/Figures/fortworth_subplots_3.tif',bbox_inches='tight')

plt.show()

# Visualize Ground Truth (the one relabeled to match GSV classification)

### Vancouver

In [162]:
from matplotlib.colors import BoundaryNorm

file_path_gt_vancouver = 'D:/Nafiseh/building_type/ground_truth_vancouver_relabeled_based_on_gsv_3.png'

visualize_and_save_figure(gt_image_arrayy_gsv, file_path_gt_vancouver)

In [67]:
plt.imshow(gt_image_arrayy_gsv)

plt.show()

#### Save GSV Map

In [74]:
from PIL import Image

from PIL.Image import Resampling

import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from matplotlib.colors import ListedColormap

##############################################################

gsv_vancouver = np.array(Image.open('D:/Nafiseh/building_type/GSV_Vancouver_Predicted_Map_2.tif').resize((2560,2560), resample=Resampling.NEAREST))

print(gsv_vancouver.shape)

print(np.unique(gsv_vancouver))

visualize_and_save_figure(gsv_vancouver, 'D:/Nafiseh/building_type/GSV_Vancouver_Predicted_Map_2_color.tif')

(2560, 2560)
[  0  17  34  51  68  85 102 255]


#### Calculate Pixel-Based Accuracy GSV (Vancouver)

In [37]:
from PIL import Image

from sklearn.metrics import classification_report

class_names = ['apartment','church','house','industrial','office building','other','retail','background']

gt_vancouver = np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\vancouver_test_region\vancouver_groundtruth_gray.png'))

gt_vancouver_,_ = make_gt_labels_same_as_gsv(gt_vancouver,gsv_vancouver)

print(gt_vancouver_.shape)

print(np.unique(gt_vancouver_))

print(classification_report(np.ravel(gt_vancouver_),np.ravel(gsv_vancouver), target_names = class_names))

(2560, 2560)
[  0  17  34  51  85  95 102 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

      apartment       0.47      0.17      0.25   1095697
         church       0.00      0.00      0.00     15902
          house       0.05      0.15      0.07    118750
     industrial       0.00      0.00      0.00     43668
office building       0.01      0.03      0.02    180637
          other       0.00      0.00      0.00    115192
         retail       0.09      0.05      0.07    382736
     background       0.84      0.89      0.86   4601018

       accuracy                           0.66   6553600
      macro avg       0.18      0.16      0.16   6553600
   weighted avg       0.68      0.66      0.66   6553600



#### Calculate Object-Based Accuracy GSV (Vancouver)

In [277]:
import pandas as pd

import numpy as np

from sklearn.metrics import classification_report

class_names = ['apartment','church','house','industrial','office building','other','retail','background']

df_v = pd.read_csv('D:/Nafiseh/building_type/vancouver_f1_score_and_gsv_predictions.csv', sep = '\t')

gt_and_pr_gsv_df = pd.DataFrame((df_v['GT_gsv'], df_v['Pr_GSV'])).T

gt_and_pr_gsv_df_na_dropped = gt_and_pr_gsv_df.dropna()

print(classification_report(np.array(gt_and_pr_gsv_df_na_dropped.iloc[:,0]), np.array(gt_and_pr_gsv_df_na_dropped.iloc[:,1]), target_names= class_names))

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average

                 precision    recall  f1-score   support

      apartment       0.51      0.28      0.36        89
         church       0.00      0.00      0.00        13
          house       0.25      0.03      0.06        30
     industrial       0.00      0.00      0.00         3
office building       0.00      0.00      0.00         0
          other       0.03      0.20      0.05         5
         retail       0.00      0.00      0.00         7
     background       0.00      0.00      0.00        19

       accuracy                           0.16       166
      macro avg       0.10      0.06      0.06       166
   weighted avg       0.32      0.16      0.21       166



### Fortworth

In [177]:
from matplotlib.colors import BoundaryNorm

file_path_gt_fortworth = 'D:/Nafiseh/building_type/ground_truth_fortworth_relabeled_based_on_gsv_3.png'

visualize_and_save_figure(gt_image_arrayy_f_gsv, file_path_gt_fortworth)

In [175]:
print(np.unique(gt_image_arrayy_f_gsv))

[  0  17  34  51  85  95 102 255]


### Save GSV Map (Fortworth)

In [73]:
from PIL import Image

from PIL.Image import Resampling

import numpy as np

gsv_fortworth = np.array(Image.open('D:/Nafiseh/building_type/GSV_Fortworth_Predicted_Map_2.tif').resize((5120,5120),resample = Resampling.NEAREST))

print(gsv_fortworth.shape)

print(np.unique(gsv_fortworth))

visualize_and_save_figure(gsv_fortworth, 'D:/Nafiseh/building_type/GSV_Fortworth_Predicted_Map_2_color.tif')

(5120, 5120)
[  0  17  51  68  85 102 255]


#### Calculate Pixel-Based Accuracy GSV (Fortworth)

In [53]:
from PIL import Image

import numpy as np

from sklearn.metrics import classification_report

class_names = ['apartment','church','house','industrial','office building','other','retail','background']

gt_fortworth,_ = make_gt_labels_same_as_gsv(np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\fortworth_groundtruth_gray.png')),gsv_fortworth)

print(gt_fortworth.shape)

print(np.unique(gt_fortworth))

print(classification_report(np.ravel(gt_fortworth), np.ravel(gsv_fortworth), target_names = class_names))

(5120, 5120)
[  0  17  34  51  85  95 102 255]


C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

      apartment       0.00      0.00      0.00    491512
         church       0.01      0.02      0.01    166926
          house       0.00      0.00      0.00      3596
     industrial       0.00      0.00      0.00    444049
office building       0.41      0.30      0.35   4421130
          other       0.00      0.00      0.00    315595
         retail       0.01      0.04      0.01    214216
     background       0.88      0.87      0.88  20157376

       accuracy                           0.72  26214400
      macro avg       0.16      0.15      0.16  26214400
   weighted avg       0.75      0.72      0.73  26214400



#### Calculate Object-Based Accuracy GSV (Fortworth)

In [275]:
import pandas as pd

import numpy as np

from sklearn.metrics import classification_report

########################################## Label Guide ##########################################################################

# GSV : 0 >> apartment, 1 >> church, 2 >> house, 3 >> industrial, 4 >> office building, 5 >> other, 6 >> retail, 7 >> background

# Ground Truth : 0 >> industrial, 1 >> institutional, 2 >> office building, 3 >> other, 4 >> residential, 5 >> retail, 6 >> background

#################################################################################################################################

def make_gsv_labels_same_as_gt(array):
    
    idx_res = np.where((array == 0) | (array == 2))
    
    idx_insti = np.where(array == 1)
    
    idx_indust = np.where(array == 3)
    
    idx_office = np.where(array == 4)
    
    idx_other = np.where(array == 5)
    
    idx_retail = np.where(array == 6)
    
    idx_back = np.where(array == 7)
    
    array[idx_indust] = 0
    
    array[idx_insti] = 1
    
    array[idx_office] = 2
    
    array[idx_other] = 3
    
    array[idx_res] = 4
    
    array[idx_retail] = 5
    
    array[idx_back] = 6
    
    #print(np.unique(array))
    
    return(array)

class_names = ['industrial','institutional','office building','other','residential','retail','background']

df_f = pd.read_csv('D:/Nafiseh/building_type/fortworth_f1_score_and_gsv_predictions.csv')

gt_and_pr_gsv_df_f = pd.DataFrame((df_f['GT_2'],df_f['Pr_GSV'])).T

gt_and_pr_gsv_df_na_dropped_f = gt_and_pr_gsv_df_f.dropna()

print(classification_report(np.array(gt_and_pr_gsv_df_na_dropped_f.iloc[:,0]), make_gsv_labels_same_as_gt(np.array(gt_and_pr_gsv_df_na_dropped_f.iloc[:,1])),
                           
                           target_names = class_names))

C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\Lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf

                 precision    recall  f1-score   support

     industrial       0.00      0.00      0.00         4
  institutional       0.00      0.00      0.00        15
office building       0.20      0.05      0.08        97
          other       0.22      0.42      0.29       102
    residential       0.07      0.03      0.04        74
         retail       0.08      0.29      0.12        21
     background       0.00      0.00      0.00        60

       accuracy                           0.15       373
      macro avg       0.08      0.11      0.08       373
   weighted avg       0.13      0.15      0.11       373



#### Save GSV Map

In [ ]:
from PIL import Image

import matplotlib.pyplot as plt
##############################################################

gsv_fortworth = np.array(Image.open('D:/Nafiseh/building_type/GSV_Fortworth_Predicted_Map_2.tif'))

visualize_and_save_figure(gsv_fortworth, 'D:/Nafiseh/building_type/GSV_Fortworth_Predicted_Map_2_color.tif')

# Create Subplots of Orthophoto and Ground Turth Maps

## Vancouver

In [3]:
def make_gt_labels_same_as_gsv(gt):
    
        
    gtt = np.copy(gt)

    gtt [gt == 0] = 255 #background

    gtt [gt == 29] = 0  #apartment

    gtt [gt == 38] = 85 #office building

    gtt [gt == 142] = 51 #industrial
    
    gtt [gt == 150] = 34 #house

    gtt [gt == 105] = 102 # retail
    
    gtt [gt == 179] = 17 #church

    gtt [(gt == 76) | (gt == 90)] = 95 #roof and garage >> other
    
    #gsv [gsv == 68] = 34  #there is no mixed r/c in ground truth so I relabeld them to house
    
    return(gtt)

In [15]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from PIL import Image

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

import numpy as np

ortho = np.array(Image.open('D:/Nafiseh/building_type/orthophoto_vancouver.tif'))

ground_truth = make_gt_labels_same_as_gsv(np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\vancouver_test_region\vancouver_groundtruth_gray.png')))

#####################################

blue_patch = mpatches.Patch(color = 'blue', label='apartment')

cyan_patch = mpatches.Patch(color = 'cyan', label='church')

green_patch = mpatches.Patch(color = 'green', label = 'house')

orange_patch = mpatches.Patch(color = 'orange', label = 'industrial')

darkred_patch = mpatches.Patch(color = 'darkred', label = 'office building')

red_patch = mpatches.Patch(color = 'red', label = 'other')

magenta_patch = mpatches.Patch(color = 'magenta', label = 'retail')

yellow_patch = mpatches.Patch(color = 'yellow', label = 'background')

colors = ['blue','cyan','green','orange','darkred','red','magenta', 'yellow']

u = np.unique(ground_truth)

color_bins = list(u-np.array([1]))+[256]

##########################################

plt.rcParams['font.family'] = 'Times New Roman'

plt.rcParams['font.size'] = 250

plt.rcParams['figure.figsize'] = (250,80)

fig, axes = plt.subplots(1,2)

fig.set_dpi(200)

axes[0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0].tick_params(labeltop = True, pad = 35)

axes[0].imshow(ortho, extent = [-123.136140, -123.129303, 49.280349, 49.284829])

axes[0].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3))

axes[0].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3))

axes[0].set_xlabel('(a) \n \n Longitude (deg)',fontweight='bold', fontsize = 250)

axes[0].set_ylabel('Latitude (deg)',fontweight='bold', fontsize = 250)

###############################################

axes[1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1].tick_params(labeltop = True, labelleft = False, labelright = True)

axes[1].imshow(ground_truth, cmap = ListedColormap(colors), norm = BoundaryNorm((color_bins), len(color_bins)), extent = [-123.136140, -123.129303, 49.280349, 49.284829])

axes[1].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3))

axes[1].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3))

axes[1].set_xlabel('(b) \n \n Longitude (deg)', fontweight='bold', fontsize = 250)

#axes[1].set_ylabel('Latitude (deg)', fontweight='bold', fontsize = 85)

axes[1].legend(handles=[blue_patch, cyan_patch, green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch], prop = {'size' : 250}, loc = 'right', bbox_to_anchor = (1.5, 0.5))

plt.tight_layout()

plt.savefig('D:/Nafiseh/building_type/Building_Type_Manuscript/Figures/ortho_gt_vancouver_2.tif',bbox_inches='tight')

plt.show()


## Fort Worth

In [18]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from PIL import Image

from osgeo import gdal

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

ortho_gdal = gdal.Open('D:/Nafiseh/building_type/orthophoto_fortworth.tif')

ortho = np.moveaxis(ortho_gdal.ReadAsArray(),0,-1)

ground_truth = make_gt_labels_same_as_gsv(np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\fortworth_groundtruth_gray.png')))

#####################################

blue_patch = mpatches.Patch(color = 'blue', label='apartment')

cyan_patch = mpatches.Patch(color = 'cyan', label='church')

green_patch = mpatches.Patch(color = 'green', label = 'house')

orange_patch = mpatches.Patch(color = 'orange', label = 'industrial')

darkred_patch = mpatches.Patch(color = 'darkred', label = 'office building')

red_patch = mpatches.Patch(color = 'red', label = 'other')

magenta_patch = mpatches.Patch(color = 'magenta', label = 'retail')

yellow_patch = mpatches.Patch(color = 'yellow', label = 'background')

colors = ['blue','cyan','green','orange','darkred','red','magenta', 'yellow']

u = np.unique(ground_truth)

color_bins = list(u-np.array([1]))+[256]

##########################################

plt.rcParams['font.family'] = 'Times New Roman'

plt.rcParams['font.size'] = 250

plt.rcParams['figure.figsize'] = (250,80)

fig, axes = plt.subplots(1,2)

fig.set_dpi(200)

axes[0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0].tick_params(labeltop = True, pad = 35)

axes[0].imshow(ortho[:,:,:3], extent = [-97.340242, -97.326509, 32.746281, 32.757833])

axes[0].set_xticks(np.round(np.arange(-97.340242, -97.326509, 0.005),3))

axes[0].set_yticks(np.round(np.arange(32.746281, 32.757833, 0.005),3))

axes[0].set_xlabel('(a) \n \n Longitude (deg)',fontweight='bold', fontsize = 250)

axes[0].set_ylabel('Latitude (deg)',fontweight='bold', fontsize = 250)

###############################################

axes[1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1].tick_params(labeltop = True, labelleft = False, labelright = True)

axes[1].imshow(ground_truth, cmap = ListedColormap(colors), norm = BoundaryNorm((color_bins), len(color_bins)), extent = [-97.340242, -97.326509, 32.746281, 32.757833])

axes[1].set_xticks(np.round(np.arange(-97.340242, -97.326590, 0.005),3))

axes[1].set_yticks(np.round(np.arange(32.746281, 32.757833, 0.005),3))

axes[1].set_xlabel('(b) \n \n Longitude (deg)', fontweight='bold', fontsize = 250)

#axes[1].set_ylabel('Latitude (deg)', fontweight='bold', fontsize = 85)

axes[1].legend(handles=[blue_patch, cyan_patch, green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch], loc = 'right', prop = {'size': 250}, bbox_to_anchor = (1.7, 0.5))

plt.tight_layout()

plt.savefig('D:/Nafiseh/building_type/Building_Type_Manuscript/Figures/ortho_gt_fortworth_2.tif',bbox_inches='tight')

plt.show()


# Ground Truths Side By Side

In [33]:
import matplotlib.pyplot as plt

import matplotlib.patches as mpatches

from PIL import Image

from matplotlib.colors import ListedColormap

from matplotlib.colors import BoundaryNorm

import numpy as np

ground_truth = make_gt_labels_same_as_gsv(np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\vancouver_test_region\vancouver_groundtruth_gray.png')))

ground_truth_2 = make_gt_labels_same_as_gsv(np.array(Image.open(r'F:\Backup_Nafiseh_Hard_Drives\BIC_GSV.tar\BIC_GSV\fortworth_test_region\fortworth_groundtruth_gray.png')))

#####################################

blue_patch = mpatches.Patch(color = 'blue', label='apartment')

cyan_patch = mpatches.Patch(color = 'cyan', label='church')

green_patch = mpatches.Patch(color = 'green', label = 'house')

orange_patch = mpatches.Patch(color = 'orange', label = 'industrial')

darkred_patch = mpatches.Patch(color = 'darkred', label = 'office building')

red_patch = mpatches.Patch(color = 'red', label = 'other')

magenta_patch = mpatches.Patch(color = 'magenta', label = 'retail')

yellow_patch = mpatches.Patch(color = 'yellow', label = 'background')

handles=[blue_patch, cyan_patch, green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch]

labels=['apartment','church','house','industrial','office building','other','retail','background']

colors = ['blue','cyan','green','orange','darkred','red','magenta', 'yellow']

u = np.unique(ground_truth)

color_bins = list(u-np.array([1]))+[256]

##########################################

plt.rcParams['font.family'] = 'Times New Roman'

plt.rcParams['font.size'] = 250

plt.rcParams['figure.figsize'] = (250,80)

fig, axes = plt.subplots(1,2)

fig.set_dpi(200)

axes[0].get_xaxis().get_major_formatter().set_useOffset(False)

axes[0].get_yaxis().get_major_formatter().set_useOffset(False)

axes[0].tick_params(labeltop = True, pad = 35)

axes[0].imshow(ground_truth, cmap = ListedColormap(colors), norm = BoundaryNorm((color_bins), len(color_bins)), extent = [-123.136140, -123.129303, 49.280349, 49.284829])

axes[0].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3))

axes[0].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3))

axes[0].set_xlabel('(a) \n \n Longitude (deg)',fontweight='bold', fontsize = 250)

axes[0].set_ylabel('Latitude (deg)',fontweight='bold', fontsize = 250)

###############################################
u = np.unique(ground_truth_2)

color_bins = list(u-np.array([1]))+[256]
###############################################

axes[1].get_xaxis().get_major_formatter().set_useOffset(False)

axes[1].get_yaxis().get_major_formatter().set_useOffset(False)

axes[1].tick_params(labeltop = True, labelleft = False, labelright = True)

axes[1].imshow(ground_truth_2, cmap = ListedColormap(colors), norm = BoundaryNorm((color_bins), len(color_bins)), extent = [-97.340242, -97.326509, 32.746281, 32.757833])

#axes[1].set_xticks(np.round(np.arange(-123.136140, -123.129303, 0.003),3))

#axes[1].set_yticks(np.round(np.arange(49.280349, 49.284829, 0.002),3))

axes[1].set_xticks(np.round(np.arange(-97.340242, -97.326590, 0.005),3))

axes[1].set_yticks(np.round(np.arange(32.746281, 32.757833, 0.005),3))

axes[1].set_xlabel('(b) \n \n Longitude (deg)', fontweight='bold', fontsize = 250)

#axes[1].set_ylabel('Latitude (deg)', fontweight='bold', fontsize = 85)

#axes[1].legend(handles=[blue_patch, cyan_patch, green_patch, orange_patch, darkred_patch, red_patch, magenta_patch, yellow_patch], prop = {'size' : 250}, loc = 'right', bbox_to_anchor = (-0.05, 0.05))

fig.legend(handles,labels,loc='lower center')

plt.tight_layout()

plt.savefig('D:/Nafiseh/building_type/Building_Type_Manuscript/Figures/Ground_Truth_2.tif',bbox_inches='tight')

plt.show()
